# Generated by Django 5.2.8 on 2025-11-13 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IrradiationRequestForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "irf_number",
                    models.CharField(
                        help_text="Sequential number following last two digits of year (e.g. 95-1, 95-2)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                (
                    "sample_description",
                    models.TextField(
                        help_text="Describe the sample material (e.g. dried tobacco leaves, powdered milk, gold foil)"
                    ),
                ),
                (
                    "physical_form",
                    models.CharField(
                        choices=[
                            ("powder", "Powder"),
                            ("ash", "Ash"),
                            ("liquid", "Liquid"),
                            ("solid", "Solid"),
                            ("foil", "Foil"),
                            ("pellet", "Pellet"),
                            ("wire", "Wire"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "physical_form_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify if 'Other' selected",
                        max_length=100,
                    ),
                ),
                (
                    "encapsulation",
                    models.CharField(
                        choices=[("poly_vial", "Poly-Vial"), ("other", "Other")],
                        default="poly_vial",
                        max_length=50,
                    ),
                ),
                (
                    "encapsulation_other",
                    models.CharField(
                        blank=True,
                        help_text="Describe if 'Other' selected",
                        max_length=200,
                    ),
                ),
                (
                    "irradiation_location",
                    models.CharField(
                        help_text="Select irradiation facility. Multiple may be authorized on single IRF",
                        max_length=200,
                    ),
                ),
                (
                    "irradiation_location_other",
                    models.CharField(
                        blank=True,
                        help_text="Describe location (e.g. 'wire stringer in Grid Position C-3')",
                        max_length=200,
                    ),
                ),
                (
                    "max_power",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum reactor power (kW) for irradiation",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_time",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Irradiation time (minutes) at maximum power",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_mass",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Maximum sample mass (grams) to be irradiated in single irradiation",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expected_dose_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected 1 foot dose rate (mrem/hr) when sample exits reactor",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dose_rate_basis",
                    models.CharField(
                        choices=[
                            ("experience", "Experience"),
                            ("calculations", "Calculations"),
                            ("unknown", "Completely Unknown"),
                        ],
                        default="experience",
                        max_length=20,
                    ),
                ),
                (
                    "dose_rate_reference_irf",
                    models.CharField(
                        blank=True,
                        help_text="Reference IRF number if based on experience",
                        max_length=20,
                    ),
                ),
                (
                    "dose_rate_calculation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Calculation method and details if applicable",
                    ),
                ),
                (
                    "reactivity_worth",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Expected reactivity worth (% Δk/k). Total of all experiments limited to 1.2%",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1.2),
                        ],
                    ),
                ),
                (
                    "reactivity_basis",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("experience", "Experience"),
                            ("sop306", "SOP 306 Calculations"),
                            ("unknown", "Completely Unknown"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                (
                    "reactivity_reference_irf",
                    models.CharField(
                        blank=True,
                        help_text="Reference IRF number if based on experience",
                        max_length=20,
                    ),
                ),
                (
                    "request_comments",
                    models.TextField(
                        blank=True, help_text="Additional comments from requester"
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(
                        help_text="Person completing the irradiation request",
                        max_length=200,
                    ),
                ),
                ("requester_signature_date", models.DateField(blank=True, null=True)),
                (
                    "reactivity_hazard",
                    models.CharField(
                        choices=[("none", "None"), ("other", "Other")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("reactivity_hazard_notes", models.TextField(blank=True)),
                (
                    "dose_rate_hazard",
                    models.CharField(
                        choices=[("none", "None"), ("other", "Other")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("dose_rate_hazard_notes", models.TextField(blank=True)),
                (
                    "reactor_equipment_hazard",
                    models.CharField(
                        choices=[("none", "None"), ("other", "Other")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("reactor_equipment_hazard_notes", models.TextField(blank=True)),
                (
                    "other_hazard",
                    models.CharField(
                        choices=[("none", "None"), ("other", "Other")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("other_hazard_notes", models.TextField(blank=True)),
                (
                    "additional_restrictions",
                    models.TextField(
                        blank=True,
                        help_text="Additional restrictions or requirements from reviewers",
                    ),
                ),
                (
                    "approver1_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("director", "Director"),
                            ("manager", "Manager"),
                            ("sro", "SRO"),
                            ("health_physicist", "Health Physicist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approver1_name", models.CharField(blank=True, max_length=200)),
                ("approver1_date", models.DateField(blank=True, null=True)),
                (
                    "approver2_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("director", "Director"),
                            ("manager", "Manager"),
                            ("sro", "SRO"),
                            ("health_physicist", "Health Physicist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approver2_name", models.CharField(blank=True, max_length=200)),
                ("approver2_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Irradiation Request Form",
                "verbose_name_plural": "Irradiation Request Forms",
                "ordering": ["-irf_number"],
            },
        ),
        migrations.CreateModel(
            name="SampleIrradiationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "irradiation_date",
                    models.DateField(help_text="Date of sample irradiation"),
                ),
                (
                    "sample_id",
                    models.CharField(
                        help_text="Sample identification number or name", max_length=100
                    ),
                ),
                (
                    "experimenter_name",
                    models.CharField(
                        help_text="Name of experimenter responsible for the sample",
                        max_length=200,
                    ),
                ),
                (
                    "actual_location",
                    models.CharField(
                        help_text="Actual irradiation location used", max_length=200
                    ),
                ),
                (
                    "actual_power",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Power level (kW) at which irradiation was performed",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "time_in",
                    models.TimeField(help_text="Console time when irradiation began"),
                ),
                (
                    "time_out",
                    models.TimeField(help_text="Console time when irradiation ended"),
                ),
                (
                    "total_time",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total irradiation time (minutes)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "measured_dose_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="1 foot dose rate (mrem/hr) from sample at initial handling",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "decay_time",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Approximate decay time (minutes) between end of irradiation and dose rate measurement",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "operator_initials",
                    models.CharField(
                        help_text="Console operator or experimenter initials",
                        max_length=10,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this irradiation"
                    ),
                ),
                (
                    "irf",
                    models.ForeignKey(
                        help_text="Associated Irradiation Request Form",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irradiation_logs",
                        to="irradiation.irradiationrequestform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Irradiation Log",
                "verbose_name_plural": "Sample Irradiation Logs",
                "ordering": ["-irradiation_date", "-time_in"],
            },
        ),
    ]
