# Generated by Django 5.2.8 on 2025-11-13 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irradiation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="irradiationrequestform",
            name="max_mass_unit",
            field=models.CharField(
                choices=[
                    ("g", "grams (g)"),
                    ("kg", "kilograms (kg)"),
                    ("mg", "milligrams (mg)"),
                ],
                default="g",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="irradiationrequestform",
            name="max_power_unit",
            field=models.CharField(
                choices=[
                    ("kw", "kW (kilowatts)"),
                    ("mw", "MW (megawatts)"),
                    ("w", "W (watts)"),
                ],
                default="kw",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="irradiationrequestform",
            name="max_time_unit",
            field=models.CharField(
                choices=[("min", "minutes"), ("hr", "hours"), ("sec", "seconds")],
                default="min",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="irradiationrequestform",
            name="sop306_calculation_file",
            field=models.FileField(
                blank=True,
                help_text="Upload SOP 306 calculation file (PDF, Excel, etc.)",
                null=True,
                upload_to="sop306_calculations/",
            ),
        ),
        migrations.AlterField(
            model_name="irradiationrequestform",
            name="max_mass",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Maximum sample mass to be irradiated in single irradiation",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="irradiationrequestform",
            name="max_power",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Maximum reactor power for irradiation",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="irradiationrequestform",
            name="max_time",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Irradiation time at maximum power",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
