# Generated by Django 5.2.8 on 2025-11-13 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irradiation", "0002_irradiationrequestform_max_mass_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irradiationrequestform",
            name="change_notes",
            field=models.TextField(
                blank=True, help_text="Notes about what changed in this version"
            ),
        ),
        migrations.AddField(
            model_name="irradiationrequestform",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("fix", "Minor Fix/Correction"),
                    ("amendment", "Amendment"),
                ],
                default="original",
                help_text="Type of change from previous version",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="irradiationrequestform",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous version if this is an amendment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amendments",
                to="irradiation.irradiationrequestform",
            ),
        ),
        migrations.AddField(
            model_name="irradiationrequestform",
            name="version_number",
            field=models.IntegerField(
                default=1, help_text="Version number for this IRF (1, 2, 3, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="irradiationrequestform",
            name="max_power_unit",
            field=models.CharField(
                choices=[
                    ("kw", "kW (kilowatts)"),
                    ("mw", "mW (milliwatts)"),
                    ("w", "W (watts)"),
                ],
                default="kw",
                max_length=10,
            ),
        ),
    ]
