# Generated by Django 5.2.8 on 2025-11-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irradiation", "0004_add_time_unit_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleirradiationlog',
            old_name='sample_id',
            new_name='sample_id_text',
        ),
    ]
