# Generated by Django 5.2.8 on 2025-11-14 16:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irradiation", "0005_rename_sample_id_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        help_text="Unique sample identifier (case-insensitive)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive name for the sample",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the sample"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        help_text="Material composition (e.g., Aluminum, Copper, Gold, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "physical_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("powder", "Powder"),
                            ("ash", "Ash"),
                            ("liquid", "Liquid"),
                            ("solid", "Solid"),
                            ("foil", "Foil"),
                            ("pellet", "Pellet"),
                            ("wire", "Wire"),
                            ("other", "Other"),
                        ],
                        help_text="Physical form of the sample",
                        max_length=50,
                    ),
                ),
                (
                    "mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Sample mass",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mass_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "grams (g)"),
                            ("kg", "kilograms (kg)"),
                            ("mg", "milligrams (mg)"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Physical dimensions (e.g., '2cm x 3cm x 0.1mm')",
                        max_length=200,
                    ),
                ),
                (
                    "is_combo",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a combination of multiple base samples",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date sample was added to database"
                    ),
                ),
                ("updated_date", models.DateField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this sample"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
                "ordering": ["sample_id"],
            },
        ),
        migrations.AlterField(
            model_name="sampleirradiationlog",
            name="decay_time",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Approximate decay time between end of irradiation and dose rate measurement",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="sampleirradiationlog",
            name="sample_id_text",
            field=models.CharField(
                help_text="Sample identification number or name (text-based, for historical records)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sampleirradiationlog",
            name="total_time",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total irradiation time",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="sampleirradiationlog",
            name="sample",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to sample in database (optional, for tracking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="irradiation_logs",
                to="irradiation.sample",
            ),
        ),
        migrations.CreateModel(
            name="SampleComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order of this component in the combo (for display purposes)",
                    ),
                ),
                (
                    "combo_sample",
                    models.ForeignKey(
                        help_text="The combo sample",
                        limit_choices_to={"is_combo": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_components",
                        to="irradiation.sample",
                    ),
                ),
                (
                    "component_sample",
                    models.ForeignKey(
                        help_text="A base sample that is part of this combo",
                        limit_choices_to={"is_combo": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_combos",
                        to="irradiation.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Component",
                "verbose_name_plural": "Sample Components",
                "ordering": ["combo_sample", "order"],
                "unique_together": {("combo_sample", "component_sample")},
            },
        ),
    ]
