# Generated by Django 5.2.8 on 2025-11-14 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irradiation", "0006_sample_alter_sampleirradiationlog_decay_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FluxConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("bare_rabbit", "Bare Rabbit"),
                            ("cad_rabbit", "Cad Rabbit"),
                            ("beam_port", "Beam Port"),
                            ("thermal_column", "Thermal Column"),
                            ("other", "Other"),
                        ],
                        help_text="Irradiation location",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "reference_power",
                    models.DecimalField(
                        decimal_places=2,
                        default=200.0,
                        help_text="Reference power in kW (default: 200 kW)",
                        max_digits=10,
                    ),
                ),
                (
                    "thermal_flux",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Thermal neutron flux at reference power (n/cm²/s)",
                        max_digits=15,
                    ),
                ),
                (
                    "fast_flux",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fast neutron flux at reference power (n/cm²/s)",
                        max_digits=15,
                    ),
                ),
                (
                    "intermediate_flux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Intermediate neutron flux (0.5 eV < E < 0.1 MeV) at reference power (n/cm²/s)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "cadmium_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cadmium ratio for this location (optional)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about flux measurements"
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flux Configuration",
                "verbose_name_plural": "Flux Configurations",
                "ordering": ["location"],
            },
        ),
        migrations.CreateModel(
            name="ActivationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "irradiation_hash",
                    models.CharField(
                        help_text="SHA256 hash of irradiation log IDs and parameters",
                        max_length=64,
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this calculation was performed"
                    ),
                ),
                (
                    "reference_time",
                    models.DateTimeField(
                        help_text="Reference time for reported activities"
                    ),
                ),
                (
                    "total_activity_bq",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Total activity in Becquerels at reference time",
                        max_digits=20,
                    ),
                ),
                (
                    "estimated_dose_rate_1ft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated dose rate at 1 foot (mrem/hr)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "isotopic_inventory",
                    models.JSONField(help_text="Complete isotopic inventory as JSON"),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="multi-group",
                        help_text="Method used (one-group, multi-group, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "number_of_isotopes",
                    models.IntegerField(help_text="Number of isotopes in inventory"),
                ),
                (
                    "calculation_successful",
                    models.BooleanField(
                        default=True,
                        help_text="Whether calculation completed successfully",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if calculation failed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Calculation notes and assumptions"
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="Sample these results belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_results",
                        to="irradiation.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activation Result",
                "verbose_name_plural": "Activation Results",
                "ordering": ["-calculated_at"],
                "unique_together": {("sample", "irradiation_hash")},
            },
        ),
        migrations.CreateModel(
            name="SampleComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element",
                    models.CharField(
                        help_text="Element symbol (e.g., Au, Al, Cu)", max_length=3
                    ),
                ),
                (
                    "isotope",
                    models.CharField(
                        blank=True,
                        help_text="Specific isotope (e.g., Au-197) or blank for natural abundance",
                        max_length=10,
                    ),
                ),
                (
                    "fraction",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Percentage of this element in the sample",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "composition_type",
                    models.CharField(
                        choices=[
                            ("wt", "Weight Percent (wt%)"),
                            ("at", "Atomic Percent (at%)"),
                        ],
                        default="wt",
                        help_text="Type of composition (weight % or atomic %)",
                        max_length=2,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="Sample this composition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition_elements",
                        to="irradiation.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Composition",
                "verbose_name_plural": "Sample Compositions",
                "ordering": ["sample", "order"],
                "unique_together": {("sample", "element", "isotope")},
            },
        ),
    ]
