# Generated by Django 3.2 on 2025-11-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irradiation', '0010_remove_version_suffixes_from_irf_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradiationrequestform',
            name='irradiation_location',
            field=models.CharField(choices=[('bare_rabbit', 'Bare Rabbit'), ('cad_rabbit', 'Cad Rabbit'), ('beam_port', 'Beam Port'), ('thermal_column', 'Thermal Column'), ('other', 'Other')], help_text='Select irradiation facility. Multiple may be authorized on single IRF', max_length=200),
        ),
        migrations.AlterField(
            model_name='sampleirradiationlog',
            name='actual_location',
            field=models.CharField(choices=[('bare_rabbit', 'Bare Rabbit'), ('cad_rabbit', 'Cad Rabbit'), ('beam_port', 'Beam Port'), ('thermal_column', 'Thermal Column'), ('other', 'Other')], help_text='Actual irradiation location used', max_length=200),
        ),
    ]
