# Generated by Django 3.2 on 2025-11-15 03:03

from django.db import migrations


def normalize_locations(apps, schema_editor):
    """
    Normalize location values from human-readable format to database format.
    E.g., "Bare Rabbit" -> "bare_rabbit"
    """
    IrradiationRequestForm = apps.get_model('irradiation', 'IrradiationRequestForm')
    SampleIrradiationLog = apps.get_model('irradiation', 'SampleIrradiationLog')

    # Mapping from various formats to standard database values
    location_map = {
        # Human-readable to database format
        'Bare Rabbit': 'bare_rabbit',
        'bare rabbit': 'bare_rabbit',
        'BARE RABBIT': 'bare_rabbit',
        'Bare_Rabbit': 'bare_rabbit',

        'Cad Rabbit': 'cad_rabbit',
        'cad rabbit': 'cad_rabbit',
        'CAD RABBIT': 'cad_rabbit',
        'Cad_Rabbit': 'cad_rabbit',
        'Cadmium Rabbit': 'cad_rabbit',
        'cadmium rabbit': 'cad_rabbit',

        'Beam Port': 'beam_port',
        'beam port': 'beam_port',
        'BEAM PORT': 'beam_port',
        'Beam_Port': 'beam_port',

        'Thermal Column': 'thermal_column',
        'thermal column': 'thermal_column',
        'THERMAL COLUMN': 'thermal_column',
        'Thermal_Column': 'thermal_column',

        'Other': 'other',
        'other': 'other',
        'OTHER': 'other',
    }

    # Update IrradiationRequestForm locations
    for irf in IrradiationRequestForm.objects.all():
        if irf.irradiation_location:
            # Handle comma-separated locations
            locations = [loc.strip() for loc in irf.irradiation_location.split(',')]
            normalized_locations = []

            for loc in locations:
                # Try direct mapping first
                if loc in location_map:
                    normalized_locations.append(location_map[loc])
                # If already in database format, keep it
                elif loc in ['bare_rabbit', 'cad_rabbit', 'beam_port', 'thermal_column', 'other']:
                    normalized_locations.append(loc)
                else:
                    # Unknown location - default to 'other'
                    normalized_locations.append('other')
                    if loc:  # If there was a custom location, preserve it in the 'other' field
                        irf.irradiation_location_other = loc

            irf.irradiation_location = ','.join(normalized_locations)
            irf.save()

    # Update SampleIrradiationLog actual_location
    for log in SampleIrradiationLog.objects.all():
        if log.actual_location:
            loc = log.actual_location.strip()

            # Try direct mapping
            if loc in location_map:
                log.actual_location = location_map[loc]
                log.save()
            # If already in database format, no change needed
            elif loc in ['bare_rabbit', 'cad_rabbit', 'beam_port', 'thermal_column', 'other']:
                pass  # Already correct
            else:
                # Unknown location - default to 'other'
                log.actual_location = 'other'
                log.save()


def reverse_normalize_locations(apps, schema_editor):
    """
    Reverse migration - convert from database format back to human-readable.
    This is a best-effort reversal since we don't know the original casing.
    """
    IrradiationRequestForm = apps.get_model('irradiation', 'IrradiationRequestForm')
    SampleIrradiationLog = apps.get_model('irradiation', 'SampleIrradiationLog')

    reverse_map = {
        'bare_rabbit': 'Bare Rabbit',
        'cad_rabbit': 'Cad Rabbit',
        'beam_port': 'Beam Port',
        'thermal_column': 'Thermal Column',
        'other': 'Other',
    }

    # Update IrradiationRequestForm locations
    for irf in IrradiationRequestForm.objects.all():
        if irf.irradiation_location:
            locations = [loc.strip() for loc in irf.irradiation_location.split(',')]
            readable_locations = [reverse_map.get(loc, loc) for loc in locations]
            irf.irradiation_location = ','.join(readable_locations)
            irf.save()

    # Update SampleIrradiationLog actual_location
    for log in SampleIrradiationLog.objects.all():
        if log.actual_location:
            log.actual_location = reverse_map.get(log.actual_location, log.actual_location)
            log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('irradiation', '0011_auto_20251115_0257'),
    ]

    operations = [
        migrations.RunPython(normalize_locations, reverse_normalize_locations),
    ]
