# Generated by Django 3.2.24 on 2025-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irradiation', '0013_activation_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationresult',
            name='estimated_dose_rate_1ft',
            field=models.FloatField(blank=True, help_text='Estimated dose rate at 1 foot (mrem/hr)', null=True),
        ),
        migrations.AlterField(
            model_name='activationtimeline',
            name='estimated_dose_rate_1ft',
            field=models.FloatField(blank=True, help_text='Estimated dose rate at 1 foot (mrem/hr)', null=True),
        ),
    ]
